### ISSUE TITLE
Add Icon to PDF files (proper way)

### ISSUE THREAD

**Issue by caprioara** [caprioara/pseudo_elements#1]
### Code

```html
<p>Pellentesque <a href="example.pdf">habitant</a> morbi tristique senectus et netus et malesuada fames ac turpis
        egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet
        quam egestas semper. Aenean ultricies mi vitae est. <a href="https://#" target="_blank">Mauris placerat</a>
        eleifend leo.</p>
```

```scss
a[href$=".pdf"]::after {
    font-family: 'Font Awesome 5 Free';
    content: '\f1c1';
}
```

### Design in template

![Screenshot_10](https://user-images.githubusercontent.com/32924546/94375968-15210980-0120-11eb-8f19-94f4c6b181a2.jpg)
